name: PHPStan

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  run:
    name: Run PHPStan
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        level: [ 1, 2 ]
        include:
          - current-level: 1
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@0f7f1d08e3e32076e51cae65eb0b0c871405b16e # v2.34.1
        with:
          php-version: '8.4'

      - name: Install PHPStan
        run: composer install

      - name: Restore cached baseline for PHPStan
        id: cache-baseline-restore
        uses: actions/cache/restore@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: |
            test/phpstan-baseline.neon
          key: phpstan-baseline-${{ github.run_id }}"
          restore-keys: |
            phpstan-baseline-

      - name: Run PHPStan
        if: matrix.level < matrix.current-level || matrix.level == matrix.current-level
        run: |
          ./vendor/bin/phpstan analyse --memory-limit 1G -c test/phpstan.neon src test -l "${{ matrix.level }}"

      - name: Run PHPStan
        if: matrix.level > matrix.current-level
        continue-on-error: true
        run: |
          ./vendor/bin/phpstan analyse --memory-limit 1G -c test/phpstan.neon src test -l "${{ matrix.level }}"
          exit 0
